In [ ]:
# a=7;b=8

In [4]:
a.__add__(b)

15

In [5]:
a=[i+'python' for i in 'python']

In [6]:
a

['ppython', 'ypython', 'tpython', 'hpython', 'opython', 'npython']

In [10]:
list=[1,2,3,4,6,7,8,8,10]
bb=[list[i] for i in range(len(list)) if list[i]%2==0]
bb

[2, 4, 6, 8, 8, 10]

In [12]:
def my_artihmetic(x,y):
    z1=x+y
    z2=x-y
    return z1,z2
r1,r2=my_artihmetic(7,5)

r1,r2

(12, 2)

In [13]:
def weighted_sum(*add):
    sum=0
    for i in add:
        sum=sum+i
    return sum
t1=weighted_sum(1,2,3,4,5,6)
t1


21

In [15]:
g=lambda:print('ff')
g()

ff


In [16]:
L2=[lambda x:x**2,lambda x:x**3 , lambda y:y**4]
pResult=[p(3) for p in L2]
pResult

[9, 27, 81]

In [18]:
class Asset():
    pass
asset1=Asset()
asset1.id='1'
asset1.id

'1'

In [23]:
class Asset():
    def __init__(self,id,price):
        self.id=id
        self.price=price
asset2=Asset('003',11)
asset2

In [26]:
class Asset():
    def __init__(self,id,price):
        self.__id=id
        self.__price=price
    def print_id(self):
        print('this asset id is %s' %(self.__id))
asset2=Asset('003',11)
asset2.print_id()

this asset id is 003


In [31]:
class Asset():
    def __init__(self,id,price):
        self.id=id
        self.price=price
    def print_id(self):
        print('this asset id is %s' %(self.id))

class nAsset(Asset):
    def print_id(self):
        print(self.id  )
nAssets2=nAsset('fff',22)
nAssets2.print_id()

fff


In [35]:
x=[1,2,3,4,5]
y=iter(x)
y
next(y)

1

In [41]:
def fib2(maxNum):
    index,first,second=0,0,1
    while index<maxNum:
        yield second
        first,second=second,first+second
        index+=1


for i in fib2(5):
    print(i)
a=[i for i in fib2(5)]
a


1
1
2
3
5


[1, 1, 2, 3, 5]

In [43]:
import calendar
print(calendar.month(2016,2))

   February 2016
Mo Tu We Th Fr Sa Su
 1  2  3  4  5  6  7
 8  9 10 11 12 13 14
15 16 17 18 19 20 21
22 23 24 25 26 27 28
29



In [44]:
calendar.isleap(2016)

True

In [46]:
from datetime import datetime
now=datetime.now()
now

datetime.datetime(2018, 5, 5, 18, 46, 48, 441814)

In [47]:
str(now)

'2018-05-05 18:46:48.441814'

In [49]:
now.strftime("%Y-%m-%d %H:%M:%S")

'2018-05-05 18:46:48'

In [58]:

del list

In [59]:
a=list('abc')

In [60]:
a


['a', 'b', 'c']

In [61]:
a.append("fuck")

In [62]:
a


['a', 'b', 'c', 'fuck']

In [63]:
a.extend(['yo','WTF'])
a

['a', 'b', 'c', 'fuck', 'yo', 'WTF']

In [64]:
a.insert(4,'44')
a

['a', 'b', 'c', 'fuck', '44', 'yo', 'WTF']

In [65]:
a.pop()

'WTF'

In [66]:
a


['a', 'b', 'c', 'fuck', '44', 'yo']

In [68]:
a.remove('yo')

In [69]:
a


['a', 'b', 'c', 'fuck', '44']

In [70]:
a.count('a')

1

In [71]:
a.pop(1)

'b'

In [72]:
a


['a', 'c', 'fuck', '44']

In [73]:
r1=range(5)

In [74]:
r1


range(0, 5)

In [75]:
abv=1,2,3,4,5

In [76]:
type(abv)

tuple

In [77]:
abv[0]

1

In [79]:
r2=list(r1)
r2

[0, 1, 2, 3, 4]

In [80]:
''.join(['a','b','c'])

'abc'

In [81]:
dd=['a','b']

In [82]:
type(dd)

list

In [83]:
tt={'a':1,'b':2,'c':3}
tt.items()

dict_items([('a', 1), ('b', 2), ('c', 3)])

In [84]:
tt.keys()

dict_keys(['a', 'b', 'c'])

In [85]:
tt.values()

dict_values([1, 2, 3])

In [86]:
tt['a']

1

In [87]:
tt.update(a=2,b=3,c=4)
tt

{'a': 2, 'b': 3, 'c': 4}

In [88]:
tt['d']=5

In [89]:
tt

{'a': 2, 'b': 3, 'c': 4, 'd': 5}

In [90]:
listx=[2,2,2,3,4,5]
set1=set(listx)
set1

{2, 3, 4, 5}

In [91]:
set1.add('ff')

In [92]:
set1

{2, 3, 4, 5, 'ff'}

In [93]:
import numpy as np 
array1=np.array(range(6))

In [94]:
array1

array([0, 1, 2, 3, 4, 5])

In [95]:
array1.shape=2,3
array1

array([[0, 1, 2],
       [3, 4, 5]])

In [96]:
array1.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [98]:
array1.shape()

TypeError: 'tuple' object is not callable

In [108]:
import numpy as np 

ar1=np.array(np.arange(5))
ar2=np.add(ar1,4)

ar3=np.add(ar1,ar2)
ar3

array([ 4,  6,  8, 10, 12])